Feature/boilerplate dj
MoroccanTea/PhishMeNot pull request #11
Opened 2023-11-01 18:32 UTC by white-b1nary

- Logic to validate the SSL cert 
- Tested on chrome

2023-11-01 19:23 UTC, t-idriss approved these changes

2023-11-01 20:39 UTC, barbossa2406 approved these changes

2023-11-03 21:41 UTC, MoroccanTea requested changes
Please revert manifest.json to its older version.

2023-11-04 18:51 UTC, closed without merging

2023-11-07 14:44 UTC, MoroccanTea approved these changes
Thank you for your contribution