Feature/boilerplate komoe2
MoroccanTea/PhishMeNot pull request #34
Opened 2023-11-22 08:03 UTC by Komoe2023

Bonjour Djibril Tu voudras trouver mon TAF sur l'activation et ma désactivation automatique des SCAN. Cordialement

2023-11-23 09:34 UTC, MoroccanTea commented
Nice ! Toutefois, je pense qu'il serait mieux de suivre les recommendations de @zakariaDM et stocker ce genre de variable dans une base de données...

2023-11-23 09:37 UTC, MoroccanTea commented on popup_analyse_scan.js
Je pense qu'il serait mieux de choisir une seule langue, pour l'extension lors du developpement pour éviter toute confusion. Nous verrons ca aujourd'hui.

2023-11-23 09:38 UTC, MoroccanTea commented on popup_analyse_scan.html
Tu n'as pas oublié quelque chose ici par hasard ?

2023-11-23 09:40 UTC, MoroccanTea commented on dist/background_analyse_scan.dev.js
C'est quoi le dossier dist et son contenu ?

2023-11-23 09:42 UTC, MoroccanTea requested changes
Quelques commentaires ont été ajoutés, nous verrons ca lors de la réunion d'aujourdhui si tu as un moment.

2023-11-26 12:56 UTC, Komoe2023 commented on popup_analyse_scan.js
Ok Lundi on en parle alors. cordialement

2023-11-26 13:04 UTC, Komoe2023 commented on dist/background_analyse_scan.dev.js
Justement je sais pas comment désactiver "dist" dans mon VCS. L'extension  "dist" s'ajoute automatiquement à tous mes projets lorsque je fais une nouvelle création et souvent cela me perturbe un peu. Merci de m'aider à regler ce probleme dans mon environnement de développement VSC

2023-11-26 13:05 UTC, closed without merging